//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfToHtml.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/webservices", ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name phoneNumber from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/setCertificateInitials", ReplyAction="*")]
        PdfToHtml.ServiceReference1.setCertificateInitialsResponse setCertificateInitials(PdfToHtml.ServiceReference1.setCertificateInitialsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/setCertificateInitials", ReplyAction="*")]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.setCertificateInitialsResponse> setCertificateInitialsAsync(PdfToHtml.ServiceReference1.setCertificateInitialsRequest request);
        
        // CODEGEN: Generating message contract since element name hashForSign64 from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/SignHash", ReplyAction="*")]
        PdfToHtml.ServiceReference1.SignHashResponse SignHash(PdfToHtml.ServiceReference1.SignHashRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/SignHash", ReplyAction="*")]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.SignHashResponse> SignHashAsync(PdfToHtml.ServiceReference1.SignHashRequest request);
        
        // CODEGEN: Generating message contract since element name getSigningCertResult from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getSigningCert", ReplyAction="*")]
        PdfToHtml.ServiceReference1.getSigningCertResponse getSigningCert(PdfToHtml.ServiceReference1.getSigningCertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getSigningCert", ReplyAction="*")]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getSigningCertResponse> getSigningCertAsync(PdfToHtml.ServiceReference1.getSigningCertRequest request);
        
        // CODEGEN: Generating message contract since element name getSigningCertAttrResult from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getSigningCertAttr", ReplyAction="*")]
        PdfToHtml.ServiceReference1.getSigningCertAttrResponse getSigningCertAttr(PdfToHtml.ServiceReference1.getSigningCertAttrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getSigningCertAttr", ReplyAction="*")]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getSigningCertAttrResponse> getSigningCertAttrAsync(PdfToHtml.ServiceReference1.getSigningCertAttrRequest request);
        
        // CODEGEN: Generating message contract since element name getSigningCertAttrv2Result from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getSigningCertAttrv2", ReplyAction="*")]
        PdfToHtml.ServiceReference1.getSigningCertAttrv2Response getSigningCertAttrv2(PdfToHtml.ServiceReference1.getSigningCertAttrv2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getSigningCertAttrv2", ReplyAction="*")]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getSigningCertAttrv2Response> getSigningCertAttrv2Async(PdfToHtml.ServiceReference1.getSigningCertAttrv2Request request);
        
        // CODEGEN: Generating message contract since element name getSignerIdentifierResult from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getSignerIdentifier", ReplyAction="*")]
        PdfToHtml.ServiceReference1.getSignerIdentifierResponse getSignerIdentifier(PdfToHtml.ServiceReference1.getSignerIdentifierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getSignerIdentifier", ReplyAction="*")]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getSignerIdentifierResponse> getSignerIdentifierAsync(PdfToHtml.ServiceReference1.getSignerIdentifierRequest request);
        
        // CODEGEN: Generating message contract since element name getDigestAlgResult from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getDigestAlg", ReplyAction="*")]
        PdfToHtml.ServiceReference1.getDigestAlgResponse getDigestAlg(PdfToHtml.ServiceReference1.getDigestAlgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getDigestAlg", ReplyAction="*")]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getDigestAlgResponse> getDigestAlgAsync(PdfToHtml.ServiceReference1.getDigestAlgRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCertificateInitialsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCertificateInitials", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.setCertificateInitialsRequestBody Body;
        
        public setCertificateInitialsRequest() {
        }
        
        public setCertificateInitialsRequest(PdfToHtml.ServiceReference1.setCertificateInitialsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class setCertificateInitialsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iOperator;
        
        public setCertificateInitialsRequestBody() {
        }
        
        public setCertificateInitialsRequestBody(string phoneNumber, int iOperator) {
            this.phoneNumber = phoneNumber;
            this.iOperator = iOperator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCertificateInitialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCertificateInitialsResponse", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.setCertificateInitialsResponseBody Body;
        
        public setCertificateInitialsResponse() {
        }
        
        public setCertificateInitialsResponse(PdfToHtml.ServiceReference1.setCertificateInitialsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class setCertificateInitialsResponseBody {
        
        public setCertificateInitialsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignHashRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignHash", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.SignHashRequestBody Body;
        
        public SignHashRequest() {
        }
        
        public SignHashRequest(PdfToHtml.ServiceReference1.SignHashRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class SignHashRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hashForSign64;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string displayText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int iOperator;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string signingAlg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isMultiSignature;
        
        public SignHashRequestBody() {
        }
        
        public SignHashRequestBody(string hashForSign64, string displayText, string phoneNumber, int iOperator, string signingAlg, bool isMultiSignature) {
            this.hashForSign64 = hashForSign64;
            this.displayText = displayText;
            this.phoneNumber = phoneNumber;
            this.iOperator = iOperator;
            this.signingAlg = signingAlg;
            this.isMultiSignature = isMultiSignature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignHashResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignHashResponse", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.SignHashResponseBody Body;
        
        public SignHashResponse() {
        }
        
        public SignHashResponse(PdfToHtml.ServiceReference1.SignHashResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class SignHashResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SignHashResult;
        
        public SignHashResponseBody() {
        }
        
        public SignHashResponseBody(string SignHashResult) {
            this.SignHashResult = SignHashResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSigningCertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSigningCert", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.getSigningCertRequestBody Body;
        
        public getSigningCertRequest() {
        }
        
        public getSigningCertRequest(PdfToHtml.ServiceReference1.getSigningCertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getSigningCertRequestBody {
        
        public getSigningCertRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSigningCertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSigningCertResponse", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.getSigningCertResponseBody Body;
        
        public getSigningCertResponse() {
        }
        
        public getSigningCertResponse(PdfToHtml.ServiceReference1.getSigningCertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class getSigningCertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getSigningCertResult;
        
        public getSigningCertResponseBody() {
        }
        
        public getSigningCertResponseBody(string getSigningCertResult) {
            this.getSigningCertResult = getSigningCertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSigningCertAttrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSigningCertAttr", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.getSigningCertAttrRequestBody Body;
        
        public getSigningCertAttrRequest() {
        }
        
        public getSigningCertAttrRequest(PdfToHtml.ServiceReference1.getSigningCertAttrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getSigningCertAttrRequestBody {
        
        public getSigningCertAttrRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSigningCertAttrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSigningCertAttrResponse", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.getSigningCertAttrResponseBody Body;
        
        public getSigningCertAttrResponse() {
        }
        
        public getSigningCertAttrResponse(PdfToHtml.ServiceReference1.getSigningCertAttrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class getSigningCertAttrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getSigningCertAttrResult;
        
        public getSigningCertAttrResponseBody() {
        }
        
        public getSigningCertAttrResponseBody(string getSigningCertAttrResult) {
            this.getSigningCertAttrResult = getSigningCertAttrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSigningCertAttrv2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSigningCertAttrv2", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.getSigningCertAttrv2RequestBody Body;
        
        public getSigningCertAttrv2Request() {
        }
        
        public getSigningCertAttrv2Request(PdfToHtml.ServiceReference1.getSigningCertAttrv2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getSigningCertAttrv2RequestBody {
        
        public getSigningCertAttrv2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSigningCertAttrv2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSigningCertAttrv2Response", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.getSigningCertAttrv2ResponseBody Body;
        
        public getSigningCertAttrv2Response() {
        }
        
        public getSigningCertAttrv2Response(PdfToHtml.ServiceReference1.getSigningCertAttrv2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class getSigningCertAttrv2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getSigningCertAttrv2Result;
        
        public getSigningCertAttrv2ResponseBody() {
        }
        
        public getSigningCertAttrv2ResponseBody(string getSigningCertAttrv2Result) {
            this.getSigningCertAttrv2Result = getSigningCertAttrv2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSignerIdentifierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSignerIdentifier", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.getSignerIdentifierRequestBody Body;
        
        public getSignerIdentifierRequest() {
        }
        
        public getSignerIdentifierRequest(PdfToHtml.ServiceReference1.getSignerIdentifierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getSignerIdentifierRequestBody {
        
        public getSignerIdentifierRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSignerIdentifierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSignerIdentifierResponse", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.getSignerIdentifierResponseBody Body;
        
        public getSignerIdentifierResponse() {
        }
        
        public getSignerIdentifierResponse(PdfToHtml.ServiceReference1.getSignerIdentifierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class getSignerIdentifierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getSignerIdentifierResult;
        
        public getSignerIdentifierResponseBody() {
        }
        
        public getSignerIdentifierResponseBody(string getSignerIdentifierResult) {
            this.getSignerIdentifierResult = getSignerIdentifierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDigestAlgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDigestAlg", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.getDigestAlgRequestBody Body;
        
        public getDigestAlgRequest() {
        }
        
        public getDigestAlgRequest(PdfToHtml.ServiceReference1.getDigestAlgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getDigestAlgRequestBody {
        
        public getDigestAlgRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDigestAlgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDigestAlgResponse", Namespace="http://localhost/webservices", Order=0)]
        public PdfToHtml.ServiceReference1.getDigestAlgResponseBody Body;
        
        public getDigestAlgResponse() {
        }
        
        public getDigestAlgResponse(PdfToHtml.ServiceReference1.getDigestAlgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class getDigestAlgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDigestAlgResult;
        
        public getDigestAlgResponseBody() {
        }
        
        public getDigestAlgResponseBody(string getDigestAlgResult) {
            this.getDigestAlgResult = getDigestAlgResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : PdfToHtml.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<PdfToHtml.ServiceReference1.Service1Soap>, PdfToHtml.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PdfToHtml.ServiceReference1.setCertificateInitialsResponse PdfToHtml.ServiceReference1.Service1Soap.setCertificateInitials(PdfToHtml.ServiceReference1.setCertificateInitialsRequest request) {
            return base.Channel.setCertificateInitials(request);
        }
        
        public void setCertificateInitials(string phoneNumber, int iOperator) {
            PdfToHtml.ServiceReference1.setCertificateInitialsRequest inValue = new PdfToHtml.ServiceReference1.setCertificateInitialsRequest();
            inValue.Body = new PdfToHtml.ServiceReference1.setCertificateInitialsRequestBody();
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.iOperator = iOperator;
            PdfToHtml.ServiceReference1.setCertificateInitialsResponse retVal = ((PdfToHtml.ServiceReference1.Service1Soap)(this)).setCertificateInitials(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.setCertificateInitialsResponse> PdfToHtml.ServiceReference1.Service1Soap.setCertificateInitialsAsync(PdfToHtml.ServiceReference1.setCertificateInitialsRequest request) {
            return base.Channel.setCertificateInitialsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.setCertificateInitialsResponse> setCertificateInitialsAsync(string phoneNumber, int iOperator) {
            PdfToHtml.ServiceReference1.setCertificateInitialsRequest inValue = new PdfToHtml.ServiceReference1.setCertificateInitialsRequest();
            inValue.Body = new PdfToHtml.ServiceReference1.setCertificateInitialsRequestBody();
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.iOperator = iOperator;
            return ((PdfToHtml.ServiceReference1.Service1Soap)(this)).setCertificateInitialsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PdfToHtml.ServiceReference1.SignHashResponse PdfToHtml.ServiceReference1.Service1Soap.SignHash(PdfToHtml.ServiceReference1.SignHashRequest request) {
            return base.Channel.SignHash(request);
        }
        
        public string SignHash(string hashForSign64, string displayText, string phoneNumber, int iOperator, string signingAlg, bool isMultiSignature) {
            PdfToHtml.ServiceReference1.SignHashRequest inValue = new PdfToHtml.ServiceReference1.SignHashRequest();
            inValue.Body = new PdfToHtml.ServiceReference1.SignHashRequestBody();
            inValue.Body.hashForSign64 = hashForSign64;
            inValue.Body.displayText = displayText;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.iOperator = iOperator;
            inValue.Body.signingAlg = signingAlg;
            inValue.Body.isMultiSignature = isMultiSignature;
            PdfToHtml.ServiceReference1.SignHashResponse retVal = ((PdfToHtml.ServiceReference1.Service1Soap)(this)).SignHash(inValue);
            return retVal.Body.SignHashResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.SignHashResponse> PdfToHtml.ServiceReference1.Service1Soap.SignHashAsync(PdfToHtml.ServiceReference1.SignHashRequest request) {
            return base.Channel.SignHashAsync(request);
        }
        
        public System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.SignHashResponse> SignHashAsync(string hashForSign64, string displayText, string phoneNumber, int iOperator, string signingAlg, bool isMultiSignature) {
            PdfToHtml.ServiceReference1.SignHashRequest inValue = new PdfToHtml.ServiceReference1.SignHashRequest();
            inValue.Body = new PdfToHtml.ServiceReference1.SignHashRequestBody();
            inValue.Body.hashForSign64 = hashForSign64;
            inValue.Body.displayText = displayText;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.iOperator = iOperator;
            inValue.Body.signingAlg = signingAlg;
            inValue.Body.isMultiSignature = isMultiSignature;
            return ((PdfToHtml.ServiceReference1.Service1Soap)(this)).SignHashAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PdfToHtml.ServiceReference1.getSigningCertResponse PdfToHtml.ServiceReference1.Service1Soap.getSigningCert(PdfToHtml.ServiceReference1.getSigningCertRequest request) {
            return base.Channel.getSigningCert(request);
        }
        
        public string getSigningCert() {
            PdfToHtml.ServiceReference1.getSigningCertRequest inValue = new PdfToHtml.ServiceReference1.getSigningCertRequest();
            inValue.Body = new PdfToHtml.ServiceReference1.getSigningCertRequestBody();
            PdfToHtml.ServiceReference1.getSigningCertResponse retVal = ((PdfToHtml.ServiceReference1.Service1Soap)(this)).getSigningCert(inValue);
            return retVal.Body.getSigningCertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getSigningCertResponse> PdfToHtml.ServiceReference1.Service1Soap.getSigningCertAsync(PdfToHtml.ServiceReference1.getSigningCertRequest request) {
            return base.Channel.getSigningCertAsync(request);
        }
        
        public System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getSigningCertResponse> getSigningCertAsync() {
            PdfToHtml.ServiceReference1.getSigningCertRequest inValue = new PdfToHtml.ServiceReference1.getSigningCertRequest();
            inValue.Body = new PdfToHtml.ServiceReference1.getSigningCertRequestBody();
            return ((PdfToHtml.ServiceReference1.Service1Soap)(this)).getSigningCertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PdfToHtml.ServiceReference1.getSigningCertAttrResponse PdfToHtml.ServiceReference1.Service1Soap.getSigningCertAttr(PdfToHtml.ServiceReference1.getSigningCertAttrRequest request) {
            return base.Channel.getSigningCertAttr(request);
        }
        
        public string getSigningCertAttr() {
            PdfToHtml.ServiceReference1.getSigningCertAttrRequest inValue = new PdfToHtml.ServiceReference1.getSigningCertAttrRequest();
            inValue.Body = new PdfToHtml.ServiceReference1.getSigningCertAttrRequestBody();
            PdfToHtml.ServiceReference1.getSigningCertAttrResponse retVal = ((PdfToHtml.ServiceReference1.Service1Soap)(this)).getSigningCertAttr(inValue);
            return retVal.Body.getSigningCertAttrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getSigningCertAttrResponse> PdfToHtml.ServiceReference1.Service1Soap.getSigningCertAttrAsync(PdfToHtml.ServiceReference1.getSigningCertAttrRequest request) {
            return base.Channel.getSigningCertAttrAsync(request);
        }
        
        public System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getSigningCertAttrResponse> getSigningCertAttrAsync() {
            PdfToHtml.ServiceReference1.getSigningCertAttrRequest inValue = new PdfToHtml.ServiceReference1.getSigningCertAttrRequest();
            inValue.Body = new PdfToHtml.ServiceReference1.getSigningCertAttrRequestBody();
            return ((PdfToHtml.ServiceReference1.Service1Soap)(this)).getSigningCertAttrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PdfToHtml.ServiceReference1.getSigningCertAttrv2Response PdfToHtml.ServiceReference1.Service1Soap.getSigningCertAttrv2(PdfToHtml.ServiceReference1.getSigningCertAttrv2Request request) {
            return base.Channel.getSigningCertAttrv2(request);
        }
        
        public string getSigningCertAttrv2() {
            PdfToHtml.ServiceReference1.getSigningCertAttrv2Request inValue = new PdfToHtml.ServiceReference1.getSigningCertAttrv2Request();
            inValue.Body = new PdfToHtml.ServiceReference1.getSigningCertAttrv2RequestBody();
            PdfToHtml.ServiceReference1.getSigningCertAttrv2Response retVal = ((PdfToHtml.ServiceReference1.Service1Soap)(this)).getSigningCertAttrv2(inValue);
            return retVal.Body.getSigningCertAttrv2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getSigningCertAttrv2Response> PdfToHtml.ServiceReference1.Service1Soap.getSigningCertAttrv2Async(PdfToHtml.ServiceReference1.getSigningCertAttrv2Request request) {
            return base.Channel.getSigningCertAttrv2Async(request);
        }
        
        public System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getSigningCertAttrv2Response> getSigningCertAttrv2Async() {
            PdfToHtml.ServiceReference1.getSigningCertAttrv2Request inValue = new PdfToHtml.ServiceReference1.getSigningCertAttrv2Request();
            inValue.Body = new PdfToHtml.ServiceReference1.getSigningCertAttrv2RequestBody();
            return ((PdfToHtml.ServiceReference1.Service1Soap)(this)).getSigningCertAttrv2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PdfToHtml.ServiceReference1.getSignerIdentifierResponse PdfToHtml.ServiceReference1.Service1Soap.getSignerIdentifier(PdfToHtml.ServiceReference1.getSignerIdentifierRequest request) {
            return base.Channel.getSignerIdentifier(request);
        }
        
        public string getSignerIdentifier() {
            PdfToHtml.ServiceReference1.getSignerIdentifierRequest inValue = new PdfToHtml.ServiceReference1.getSignerIdentifierRequest();
            inValue.Body = new PdfToHtml.ServiceReference1.getSignerIdentifierRequestBody();
            PdfToHtml.ServiceReference1.getSignerIdentifierResponse retVal = ((PdfToHtml.ServiceReference1.Service1Soap)(this)).getSignerIdentifier(inValue);
            return retVal.Body.getSignerIdentifierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getSignerIdentifierResponse> PdfToHtml.ServiceReference1.Service1Soap.getSignerIdentifierAsync(PdfToHtml.ServiceReference1.getSignerIdentifierRequest request) {
            return base.Channel.getSignerIdentifierAsync(request);
        }
        
        public System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getSignerIdentifierResponse> getSignerIdentifierAsync() {
            PdfToHtml.ServiceReference1.getSignerIdentifierRequest inValue = new PdfToHtml.ServiceReference1.getSignerIdentifierRequest();
            inValue.Body = new PdfToHtml.ServiceReference1.getSignerIdentifierRequestBody();
            return ((PdfToHtml.ServiceReference1.Service1Soap)(this)).getSignerIdentifierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PdfToHtml.ServiceReference1.getDigestAlgResponse PdfToHtml.ServiceReference1.Service1Soap.getDigestAlg(PdfToHtml.ServiceReference1.getDigestAlgRequest request) {
            return base.Channel.getDigestAlg(request);
        }
        
        public string getDigestAlg() {
            PdfToHtml.ServiceReference1.getDigestAlgRequest inValue = new PdfToHtml.ServiceReference1.getDigestAlgRequest();
            inValue.Body = new PdfToHtml.ServiceReference1.getDigestAlgRequestBody();
            PdfToHtml.ServiceReference1.getDigestAlgResponse retVal = ((PdfToHtml.ServiceReference1.Service1Soap)(this)).getDigestAlg(inValue);
            return retVal.Body.getDigestAlgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getDigestAlgResponse> PdfToHtml.ServiceReference1.Service1Soap.getDigestAlgAsync(PdfToHtml.ServiceReference1.getDigestAlgRequest request) {
            return base.Channel.getDigestAlgAsync(request);
        }
        
        public System.Threading.Tasks.Task<PdfToHtml.ServiceReference1.getDigestAlgResponse> getDigestAlgAsync() {
            PdfToHtml.ServiceReference1.getDigestAlgRequest inValue = new PdfToHtml.ServiceReference1.getDigestAlgRequest();
            inValue.Body = new PdfToHtml.ServiceReference1.getDigestAlgRequestBody();
            return ((PdfToHtml.ServiceReference1.Service1Soap)(this)).getDigestAlgAsync(inValue);
        }
    }
}
